version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            -   "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        # Recently, a bug was introduced with the latest Create React App version that is causing the React app to exit when starting with Docker Compose.
        stdin_open: true
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
           